### ISSUE TITLE
执行13.写入时间时报错

### ISSUE THREAD

**Issue by petermojiahua** [1299172402/everphotoDL#7]
程序出现异常，无法继续。出现的异常信息如下：
Traceback (most recent call last):
  File "main.py", line 88, in <module>
  File "main.py", line 77, in interface
  File "function\K_write_time.py", line 110, in interface
  File "function\K_write_time.py", line 57, in modify_picture_time
  File "_strptime.py", line 562, in _strptime_time
  File "_strptime.py", line 352, in _strptime
ValueError: unconverted data remains: -06:00
按下回车键继续...

**Comment by 1299172402** [comment]
你们这种什么都不说，就这么贴个代码？

**Comment by 1299172402** [comment]
解决不了问题的

**Comment by petermojiahua** [comment]
> 你们这种什么都不说，就这么贴个代码？

我还以为贴代码反而比用文字描述更方便排查问题😂具体情况就是我在执行13，然后过了一段时间就蹦出了如下错误提示
